
PATH:
  DATASET_DIR: 'dataset/'
  PKL_PATH: 'dataset/database.pkl'

INFO:
  PICTURE_PROMPT: 'This app recognizes faces in a live video stream or from uploaded images by selecting the input type option in the sidebar. To use it for recognition from uploaded images, select the "Picture" option and upload an image and the recognition will be run automatically.'
  WEBCAM_PROMPT: 'This app recognizes faces in a live video stream or from uploaded images by selecting the input type option in the sidebar. To use it for recognition from a live video stream, select the "Webcam" option and press start and allow access to your webcam and the recognition will be run automatically.'